#!/usr/bin/python3

import re
import matplotlib.pyplot as plt
import numpy as np


list_time = []
list_CPU_TEMP = []


with open('data.csv') as f:
    next(f)     #removes first line of data
    for l in f:
        l = l.strip() #removes any leading or lagging spaces

        regex = re.match(r'("[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}"),(-?[0-9]+\.[0-9]+)?,(-?[0-9]+\.[0-9]+)?,(-?[0-9]+\.[0-9]+)?,(-?[0-9]+\.[0-9]+)?,(-?[0-9]+\.[0-9]+)?,(-?[0-9]+\.[0-9]+)?,(-?[0-9]+\.[0-9]+)?,(-?[0-9]+\.[0-9]+)?,(-?[0-9]+\.[0-9]+)?',l)

        #print(regex)
        time = regex.group(1)
        CPU = float(regex.group(2))
        #print(time,CPU)
        list_time.append(time)
        list_CPU_TEMP.append(CPU)

data = np.array(list_CPU_TEMP)
plt.plot(list_time,data)
plt.show()
